#Requires -RunAsAdministrator

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$ImagePath,

    [Parameter(Mandatory = $true, Position = 1)]
    [string]$MountPoint
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Show-Usage {
    @"
Usage: .\mount-image.ps1 <image(.vhd)> <mount-point>

Mounts a makevhd-generated VHD on Windows using the built-in Storage module.

Examples:
  .\mount-image.ps1 .\disk.vhd C:\mnt\disk

Notes:
  - Run this script from an elevated PowerShell session.
  - The mount point must be an empty directory on an NTFS volume.
  - Windows does not natively mount the raw .img files generated by this project.
"@
}

function Resolve-FullPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    return [System.IO.Path]::GetFullPath($Path)
}

function Test-Administrator {
    $currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentIdentity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Ensure-StorageCmdlets {
    foreach ($cmdlet in "Mount-DiskImage", "Dismount-DiskImage", "Get-DiskImage", "Get-Disk", "Get-Partition", "Add-PartitionAccessPath", "Get-Volume") {
        if (-not (Get-Command -Name $cmdlet -ErrorAction SilentlyContinue)) {
            throw "required PowerShell cmdlet not available: $cmdlet"
        }
    }
}

function Ensure-MountPoint {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $fullPath = Resolve-FullPath -Path $Path
    $root = [System.IO.Path]::GetPathRoot($fullPath)

    if ($root -notmatch '^[A-Za-z]:\\$') {
        throw "mount point must be on a local drive path, got: $fullPath"
    }

    $driveLetter = $root.Substring(0, 1)
    $volume = Get-Volume -DriveLetter $driveLetter
    if ($volume.FileSystem -ne "NTFS") {
        throw "mount point must be on an NTFS volume, got $($volume.FileSystem) for drive $driveLetter`:"
    }

    if (-not (Test-Path -LiteralPath $fullPath)) {
        New-Item -ItemType Directory -Path $fullPath -Force | Out-Null
    }

    $item = Get-Item -LiteralPath $fullPath
    if (-not $item.PSIsContainer) {
        throw "mount point must be a directory: $fullPath"
    }

    if (Get-ChildItem -LiteralPath $fullPath -Force | Select-Object -First 1) {
        throw "mount point directory must be empty: $fullPath"
    }

    return $fullPath
}

function Get-MountedPartition {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    for ($attempt = 0; $attempt -lt 20; $attempt++) {
        $partition = Get-DiskImage -ImagePath $Path |
            Get-Disk |
            Get-Partition |
            Where-Object { $_.Size -gt 0 } |
            Select-Object -First 1

        if ($partition) {
            return $partition
        }

        Start-Sleep -Milliseconds 200
    }

    throw "no mountable partition found in VHD: $Path"
}

if (-not (Test-Administrator)) {
    Show-Usage | Write-Error
    throw "run this script from an elevated PowerShell session"
}

Ensure-StorageCmdlets

$resolvedImagePath = Resolve-FullPath -Path $ImagePath
if (-not (Test-Path -LiteralPath $resolvedImagePath -PathType Leaf)) {
    throw "image file not found: $resolvedImagePath"
}

switch ([System.IO.Path]::GetExtension($resolvedImagePath).ToLowerInvariant()) {
    ".vhd" { }
    ".img" { throw "Windows does not natively mount the raw .img files generated by this project; use a .vhd file instead" }
    default { throw "unsupported image extension: $resolvedImagePath" }
}

$resolvedMountPoint = Ensure-MountPoint -Path $MountPoint
$diskImage = Get-DiskImage -ImagePath $resolvedImagePath
$mountedByScript = $false

try {
    if (-not $diskImage.Attached) {
        Mount-DiskImage -ImagePath $resolvedImagePath | Out-Null
        $mountedByScript = $true
    }

    $partition = Get-MountedPartition -Path $resolvedImagePath
    Add-PartitionAccessPath -DiskNumber $partition.DiskNumber -PartitionNumber $partition.PartitionNumber -AccessPath $resolvedMountPoint | Out-Null

    Write-Host "mounted $resolvedImagePath at $resolvedMountPoint"
    Write-Host "unmount with: Dismount-DiskImage -ImagePath `"$resolvedImagePath`""
}
catch {
    if ($mountedByScript) {
        Dismount-DiskImage -ImagePath $resolvedImagePath -ErrorAction SilentlyContinue | Out-Null
    }

    throw
}
